language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - python -m pip install pytest-cov coveralls

# command to run tests
script:
  - python -m pytest Tests/ --cov=./
after_success:
  - coveralls